// Generated by gencpp from file egitim_araci/CemberHareket.msg
// DO NOT EDIT!


#ifndef EGITIM_ARACI_MESSAGE_CEMBERHAREKET_H
#define EGITIM_ARACI_MESSAGE_CEMBERHAREKET_H

#include <ros/service_traits.h>


#include <egitim_araci/CemberHareketRequest.h>
#include <egitim_araci/CemberHareketResponse.h>


namespace egitim_araci
{

struct CemberHareket
{

typedef CemberHareketRequest Request;
typedef CemberHareketResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CemberHareket
} // namespace egitim_araci


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::egitim_araci::CemberHareket > {
  static const char* value()
  {
    return "534fdc954659adaf837ecd56d547676d";
  }

  static const char* value(const ::egitim_araci::CemberHareket&) { return value(); }
};

template<>
struct DataType< ::egitim_araci::CemberHareket > {
  static const char* value()
  {
    return "egitim_araci/CemberHareket";
  }

  static const char* value(const ::egitim_araci::CemberHareket&) { return value(); }
};


// service_traits::MD5Sum< ::egitim_araci::CemberHareketRequest> should match
// service_traits::MD5Sum< ::egitim_araci::CemberHareket >
template<>
struct MD5Sum< ::egitim_araci::CemberHareketRequest>
{
  static const char* value()
  {
    return MD5Sum< ::egitim_araci::CemberHareket >::value();
  }
  static const char* value(const ::egitim_araci::CemberHareketRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::egitim_araci::CemberHareketRequest> should match
// service_traits::DataType< ::egitim_araci::CemberHareket >
template<>
struct DataType< ::egitim_araci::CemberHareketRequest>
{
  static const char* value()
  {
    return DataType< ::egitim_araci::CemberHareket >::value();
  }
  static const char* value(const ::egitim_araci::CemberHareketRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::egitim_araci::CemberHareketResponse> should match
// service_traits::MD5Sum< ::egitim_araci::CemberHareket >
template<>
struct MD5Sum< ::egitim_araci::CemberHareketResponse>
{
  static const char* value()
  {
    return MD5Sum< ::egitim_araci::CemberHareket >::value();
  }
  static const char* value(const ::egitim_araci::CemberHareketResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::egitim_araci::CemberHareketResponse> should match
// service_traits::DataType< ::egitim_araci::CemberHareket >
template<>
struct DataType< ::egitim_araci::CemberHareketResponse>
{
  static const char* value()
  {
    return DataType< ::egitim_araci::CemberHareket >::value();
  }
  static const char* value(const ::egitim_araci::CemberHareketResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EGITIM_ARACI_MESSAGE_CEMBERHAREKET_H
