// Generated by gencpp from file egitim_araci/Mesafe.msg
// DO NOT EDIT!


#ifndef EGITIM_ARACI_MESSAGE_MESAFE_H
#define EGITIM_ARACI_MESSAGE_MESAFE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace egitim_araci
{
template <class ContainerAllocator>
struct Mesafe_
{
  typedef Mesafe_<ContainerAllocator> Type;

  Mesafe_()
    : mesafe(0.0)  {
    }
  Mesafe_(const ContainerAllocator& _alloc)
    : mesafe(0.0)  {
  (void)_alloc;
    }



   typedef double _mesafe_type;
  _mesafe_type mesafe;





  typedef boost::shared_ptr< ::egitim_araci::Mesafe_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::egitim_araci::Mesafe_<ContainerAllocator> const> ConstPtr;

}; // struct Mesafe_

typedef ::egitim_araci::Mesafe_<std::allocator<void> > Mesafe;

typedef boost::shared_ptr< ::egitim_araci::Mesafe > MesafePtr;
typedef boost::shared_ptr< ::egitim_araci::Mesafe const> MesafeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::egitim_araci::Mesafe_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::egitim_araci::Mesafe_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::egitim_araci::Mesafe_<ContainerAllocator1> & lhs, const ::egitim_araci::Mesafe_<ContainerAllocator2> & rhs)
{
  return lhs.mesafe == rhs.mesafe;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::egitim_araci::Mesafe_<ContainerAllocator1> & lhs, const ::egitim_araci::Mesafe_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace egitim_araci

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::egitim_araci::Mesafe_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::egitim_araci::Mesafe_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::egitim_araci::Mesafe_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::egitim_araci::Mesafe_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::egitim_araci::Mesafe_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::egitim_araci::Mesafe_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::egitim_araci::Mesafe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67ce55637aff33e83a28f98ea42e7243";
  }

  static const char* value(const ::egitim_araci::Mesafe_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67ce55637aff33e8ULL;
  static const uint64_t static_value2 = 0x3a28f98ea42e7243ULL;
};

template<class ContainerAllocator>
struct DataType< ::egitim_araci::Mesafe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "egitim_araci/Mesafe";
  }

  static const char* value(const ::egitim_araci::Mesafe_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::egitim_araci::Mesafe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 mesafe\n"
;
  }

  static const char* value(const ::egitim_araci::Mesafe_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::egitim_araci::Mesafe_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mesafe);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mesafe_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::egitim_araci::Mesafe_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::egitim_araci::Mesafe_<ContainerAllocator>& v)
  {
    s << indent << "mesafe: ";
    Printer<double>::stream(s, indent + "  ", v.mesafe);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EGITIM_ARACI_MESSAGE_MESAFE_H
